sudo: required

language: minimal

services:
  - docker

env:
  global:
  - secure: D8wWA24gXjNa1bi4Gt2U5Iu3cp2AcL9FS6nDIxDDD0F7qi2gC3uZpdzfA8667LGOeLBJ6eTpUHiQ0fOm9EhTO7qJLk4RQjN3OrQwvtXWfNxb6jFuOtrwySDSbcdxvuMf/MugRAXN8egDpyhrSrJGPOy8+L9FEBgfT+yS3U5qXyb/lSJNnx1HCJ/3vy0TY5qbHO14UilN5gzty6SGSjUIVfA+0pta9LCrC9/Nl4ZsXhtKxFbdiMZZYClaODujIulHiNgcFJpDR/8OSE2g9MhR/omJLCPmrbEe5UJG8SwUr3Wg+RAa27UrtzgM46TMKwajklJxUDTmfWvWGlg31oSMMscLmupylU+Ls1BcqN9aNulxpmtEx1jwGQubD9pxh/zIL655f0DRgmDIA/SjEUnAO2zys1Z/R0Vu/p9Pjb8GEKUjj54z1xGrKzphBvuxsgnW8IhJtttqdAz9GUzNDRSvdN2TJCyzy5JSLfv+JsFaztSBRnnu8HEwpKDo28Qew1nO+91RPd5W36iR/2XkJqq6hJdl4NnjAc7RZ0BOPrbVqv9HdH19CTso9KoszWaAfz/O3PeB8QvSJDlwObhyh7GPwNQsC24Y0KHvEagoK+5fhzR0x9WMHTpJdUHzh3z2eVjbysVqe2TyYa8y3UuN+Qlale1I7zNNg6EyY0+utHN1dlg=
  - secure: c6IBNcbJp0G3OZie/bwF4SzAtXieh6/N8iy+J3w6La3dX+bYpslV1/jwFR0ej25BlAWdeb9YumnYBPzuet5ISdybJc2GoSANO/vFzphK9/U3m4da3OElRLAkY14hIQVkVz4SrkNxzHssdI2YEjvLF6M8THwlqHwTpcRtNXJJHUHBxQAPble98Ikv5ErQz3d6D8p8+zqp8biP6PEKEpN6W6s0tM+YDuu4EeU8aN0jjsu+EndVO8VWYCNUHHk7yqOikXokS+zBb3G3c73nCL43fMtXPRzjMmPQXqJNi29iOrJcpjIdRqoFLPwCMs2B6YdslDVrQSE+h4W9S4n1Ygqy+/Kz1u5adUGChDrIoNUCSoPosA/TFlya6nD7TeN4REaaQpUlBIquxqhd6Oyj0v5MSRyrF8UH01B3AhpAntbzguwG7vZXx2I28IGq6p4lTpc8DYu8N27/EOSy1n/+v0bqpksNM6Dm2BVmQuVckNwUVbiCXXWIQsYRRFoW6XOwVyq+awTQJU+MQJBwszdlqW8PylCFSueM1IF2au4L9Sy8/dFXux5OgBM4v7t6xczTFf9OZNrP7+v3na5xlMwZX/od1PGzzcd8fnXa56yjlcJIXgYoYXbVUuuo+0lLSkdHaZ38ZFBYekCNQifrZn4d/tEwRgdQDuFG2la8FQNsud9Le00=
  - secure: dF0eKHteV6DAttJIScILWzF/NBHF2gsUmKXjQVMto/kcDW4rqrgKMvZ4A59ytfOsRLgg2tjjwp7nfr/z8C6LNtrQOl1Cr0w2j6I1LB7KNucrfWmqcMQ+4+WYLcozUznX16LuOnou/goCtQJRtFP/vPPYFfC1kB6GkqR78rNt+CDQkQdJwDwsjFrzA+Qwy5IZnNWcQ+MA12sNI1wJ8Vyl1BYnf9fSUeN7gNKPr/fGox+CSg9Q9Zcu1+sbkXSpljlbkYTbg/PrpNCyWKM+WG8cDT9L0aP+/y9kKnCE2X1pNyxlrMUAquJmPtSaUBmJJr1a4JqEfAo9jyFsWOgVz89xgW/36o/Xk1vC4ESjBl/mpoWwXcYaMwuAuBz+JSex6b07vd7E7G2G1Y70dZBf1BmNMMgPKMC19kkpN6FbBlpv8uz5JuRQKZeH0p4anDKPqh14W18wHPGZv7L/V1pRomTo25OZgnKJXxhtgSWBuG8oxslYa/w/9wUUDhEP8aZyeRfrPc5eQb3TQD/ngzyi7NxmxBg+RiELF4UwwAoD1RnRubUdUG8Hz0orvS14dgrx/vUn3vPEyvdnnpvLfH/gPS4Gv3pRrz11KQV3TzFyfQbj1vxk2ZEHbdgRafnuCPuBBKo+ZaPe04Jxq4fi/jFYmQHjW/sJGAJs9+FX4XDKlADvHq8=

branches:
  only:
  - master

script: make build

before_deploy:
  - git config --local user.name "${CI_USER_NAME}"
  - git config --local user.email "${CI_USER_MAIL}"
  - git remote add origin-ci https://${CI_USER_NAME}:${CI_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git &>/dev/null
  - git fetch --tags --quiet origin-ci
  - git tag -l | xargs -n 1 git push --quiet --delete origin-ci
  - export TRAVIS_TAG=$(date +'%Y-%m-%d_%H-%M-%S')
  - git tag $TRAVIS_TAG
  - git remote rm origin-ci &>/dev/null

deploy:
  provider: releases
  api_key: "${CI_TOKEN}"
  body: "${TRAVIS_BUILD_WEB_URL}"
  skip_cleanup: true
  overwrite: true
  file_glob: true
  file:
    - "*.log"
    - "*.iso"

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#nicoulaj"
    on_success: never
    on_failure: change
    on_start: never
    use_notice: true
    template:
      - "%{repository}/%{branch}#%{build_number}: %{message} | changes : %{compare_url} | build : %{build_url}"
