sudo: required

language: minimal

services:
  - docker

script: make build

before_deploy:
  - git config --local user.name "nicoulaj-archiso-ci"
  - git config --local user.email "julien.nicoulaud+github-nicoulaj-archiso-ci@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key:
    secure: SAJs8lpQBhFqmK/47MUhABD70R+lz+jkjeiewrvayPW1RYDSuZRSE2SxVSeEumSkOPlfVAEe3f3pIVmMODgGKf6EVpuU7ssCwXPb/VT5tWoqI+E3Wag3LlAherWI9hxET5m9VQmHeAGnKMZ3SqTb9YQrCPOAtoMWk7lwHDNrbRN257cPZUL9Wb7sQNhvFmq6/knbThx36Qns2WMlqh8huJVuZnny4AYs4N1dZAuixnz5ympbqK1eVc9Uf4qtNsAvSKTSf5Ar7I85jBTFXZae7K+/bjAOMiz2K8iVOfXXwJxE8gbhuF/vh4LpO/25NHePWMXpPN4VeqehtIto/fGJpjv7m9o58d2oEjXvGvIoa6RXV2tY63VdtqbV8KBEJNX8kqloCk3qKqCxp3ufbzZiNUqMlR3KfNmw4SGz7bLBsazMQ0DPc22SR6dNmsgy/OsPAQ4crujqS2K5rU3ovwq0/Wjl00JPbDEorVpcb9h3YNS/f7Pz3LCs1yDVNlWMX3UeOpFOQINoOm3woGYkE9vvcY2T3+f46f5hxyQx+R/p1f7qIwKZLA4fGi+FTw8v4VYrxElG/mkNVuItfxybbdFPlXyhnBFh4xTAespc8uX8duH9FOfSOOupTDytgJKBm0E4Fr6u+OCTME6dM20PbqT65+0ttNeQQAC3rQcsBEFx8Xk=
  skip_cleanup: true
  file_glob: true
  file: "*.iso"
  on:
    repo: nicoulaj/archiso

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#nicoulaj"
    on_success: never
    on_failure: change
    on_start: never
    use_notice: true
    template:
      - "%{repository}/%{branch}#%{build_number}: %{message} | changes : %{compare_url} | build : %{build_url}"
